-- AlterTable: 新增加拿大代理公司枚举值 OVERSEA_WALKERS_CA
ALTER TABLE `AgentInfo` MODIFY `agentCompany` ENUM('OVERSEA_WALKERS_GB', 'OVERSEA_WALKERS_EU', 'EU_CONSULTEN_SRLS', 'OVERSEA_WALKERS_US', 'OVERSEA_WALKERS_TR', 'OVERSEA_WALKERS_CA') NOT NULL;
